services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: senha_local
      POSTGRES_DB: agencia
    ports: ["5433:5432"]
    volumes: ["pgdata:/var/lib/postgresql/data"]
volumes: { pgdata: {} }